# Generated by Django 5.2.17 on 2026-09-14 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("web", "0009_supervisor_supervisor_username_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField()),
                ("module_code", models.TextField()),
                ("academic_year", models.TextField()),
                ("assessment_type", models.TextField()),
                ("ai_policy", models.TextField()),
                ("group_work_permitted", models.BooleanField(default=False)),
                ("content", models.JSONField(default=dict)),
                ("programme", models.TextField(blank=True, null=True)),
                ("module_level", models.IntegerField(blank=True, null=True)),
                ("version", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In review"),
                            ("changes_requested", "Changes requested"),
                            ("approved", "Approved"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checking_assessments",
                        to="web.supervisor",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_assessments",
                        to="web.supervisor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BriefRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("cluster_lead", "Cluster Lead"),
                            ("teaching_director", "Teaching Director"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="brief_roles_assigned",
                        to="web.supervisor",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brief_roles",
                        to="web.supervisor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClusterLeadScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("programme", models.TextField()),
                ("programme_key", models.TextField()),
                ("module_level", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cluster_lead_scopes_assigned",
                        to="web.supervisor",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_lead_scopes",
                        to="web.supervisor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("checker", "Checker"),
                            ("cluster_lead", "Cluster lead"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("changes_requested", "Changes requested"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("reviewed_version", models.IntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_assignments",
                        to="briefs.assessment",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="brief_reviews_assigned",
                        to="web.supervisor",
                    ),
                ),
                (
                    "overridden_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="brief_reviews_overridden",
                        to="web.supervisor",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="brief_reviews",
                        to="web.supervisor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessment_id", models.UUIDField()),
                ("assessment_version", models.IntegerField()),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("checker", "Checker"),
                            ("cluster_lead", "Cluster lead"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("reviewer_id", models.IntegerField(blank=True, null=True)),
                ("actor_id", models.IntegerField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("withdrawn", "Withdrawn"),
                            ("invalidated", "Invalidated"),
                            ("overridden", "Overridden"),
                        ],
                        max_length=32,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["assessment_id", "-created_at"],
                        name="briefs_revi_assessm_579096_idx",
                    ),
                    models.Index(
                        fields=["reviewer_id"], name="briefs_revi_reviewe_3cd9f4_idx"
                    ),
                    models.Index(
                        fields=["actor_id"], name="briefs_revi_actor_i_0477c1_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(fields=["owner"], name="briefs_asse_owner_i_031b57_idx"),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["checker"], name="briefs_asse_checker_cfbf30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(fields=["status"], name="briefs_asse_status_9d58fc_idx"),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["academic_year"], name="briefs_asse_academi_ab5441_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["assessment_type"], name="briefs_asse_assessm_275e1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["-updated_at"], name="briefs_asse_updated_5d29f4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("checker__isnull", True),
                    models.Q(("checker", models.F("owner")), _negated=True),
                    _connector="OR",
                ),
                name="assessments_checker_is_not_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="assessments_version_at_least_one",
            ),
        ),
        migrations.AddIndex(
            model_name="briefrole",
            index=models.Index(
                fields=["role", "supervisor"], name="briefs_brie_role_6a11c7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="briefrole",
            constraint=models.UniqueConstraint(
                fields=("supervisor", "role"), name="brief_role_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="clusterleadscope",
            index=models.Index(
                fields=["programme_key", "module_level", "supervisor"],
                name="briefs_clus_program_399ae4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="clusterleadscope",
            constraint=models.UniqueConstraint(
                fields=("supervisor", "programme_key", "module_level"),
                name="cluster_lead_scope_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewassignment",
            index=models.Index(
                fields=["reviewer"], name="briefs_revi_reviewe_1856d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewassignment",
            index=models.Index(fields=["state"], name="briefs_revi_state_4c836c_idx"),
        ),
        migrations.AddConstraint(
            model_name="reviewassignment",
            constraint=models.UniqueConstraint(
                fields=("assessment", "stage"), name="review_assignment_unique"
            ),
        ),
    ]
