# Generated by Django 5.2.17 on 2026-09-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("briefs", "0001_initial"),
        ("web", "0009_supervisor_supervisor_username_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="programme_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["programme_key", "module_level"],
                name="briefs_asse_program_a14fe0_idx",
            ),
        ),
    ]
