"""
Django settings for marking project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import sys

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)ui$b36b&5#s0k&5w#v+=5%wk7a=)_$-x0%uhnq6^(prh%s^f8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['marking.cmp.uea.ac.uk']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web',
    'briefs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'web.middleware.InjectContext',
]

ROOT_URLCONF = 'marking.urls'

# JSON, not an HTML error page, when a call under /api/ fails the CSRF check.
# Everything else still gets Django's default page.
CSRF_FAILURE_VIEW = 'briefs.api.csrf_failure'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'marking.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Pull in settings from environment
import os

def bool_from_env(name, default=None):
    v = os.getenv(name,'')

    if v=='' and default==None:
        raise ValueError(f'Required env missing "{name}"')

    if v=='' and default!=None:
        return default

    return v.lower() in ['true','yes','enable']

DEBUG = bool_from_env('WEBSITE_DEBUG', default=False)

if DEBUG:
    ALLOWED_HOSTS.extend(['localhost', '127.0.0.1'])
    # `npm run dev` in frontend/ serves the brief generator from port 3000 and
    # proxies /api/ back here, so those calls arrive with a cross-origin Origin
    # header. Development only -- production serves both from one origin.
    CSRF_TRUSTED_ORIGINS = ['http://localhost:3000', 'http://127.0.0.1:3000']

dbConfig = os.environ.get('WEBSITE_DBCONFIG',None)
if dbConfig != None:
    # HOSTNAME:DBNAME:DBUSER:PASSWORD
    parts = dbConfig.split(':')
    if len(parts) != 4:
        raise Exception('Invalid database configuration (HOSTNAME:DBNAME:DBUSER:PASSWORD)')
    
    dbHost, dbName, dbUser, dbPassword = parts
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': dbName,
            'USER': dbUser,
            'PASSWORD': dbPassword,
            'HOST': dbHost,
            'PORT': 5432,
        }
    }

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
mail_config = os.environ.get('WEBSITE_MAIL', None)
if mail_config != None:
    # Host
    if len(mail_config) < 1:
        raise Exception('Invalid mail configuration. WEBSITE_MAIL=Host')
    
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = mail_config
    #EMAIL_HOST_USER = ''
    #EMAIL_HOST_PASSWORD = ''
    #EMAIL_USE_SSL=False
    #EMAIL_PORT=25

static_root = os.environ.get('WEBSITE_STATIC',None)
if static_root == None:
    if not DEBUG:
        raise Exception('Static content directory not defined (WEBSITE_STATIC)')
else:
    STATIC_ROOT = static_root

# HIDE_PROJECTS hides projects from the student views
# HIDE_PROJECTS = bool_from_env('WEBSITE_HIDE_PROJECTS', default=False)
# READ_ONLY_MODE prevents students from requesting projects
# READ_ONLY_MODE = bool_from_env('WEBSITE_READONLY', default=False)

# SUPERVISOR_PROJECT_LOCK prevents editing/creation of projects
# SUPERVISOR_PROJECT_LOCK = bool_from_env('WEBSITE_SUPERVISOR_PROJECT_LOCK', default=False)
# SUPERVISOR_RESPONSE_LOCK prevents supervisors from accepting/rejecting requests
# SUPERVISOR_RESPONSE_LOCK = bool_from_env('WEBSITE_SUPERVISOR_RESPONSE_LOCK', default=False)

DISABLE_AD = bool_from_env('WEBSITE_DISABLE_AD', default=False)

API_SECRET_TOKEN = os.environ.get('WEBSITE_API_SECRET', None)
if API_SECRET_TOKEN==None:
    print('API_SECRET_TOKEN not defined, /api/ is disabled')

WEBSITE_URL = os.environ.get('WEBSITE_URL', None)
if WEBSITE_URL==None:
    print('WEBSITE_URL not defined (e.g. https://marking.cmp.uea.ac.uk)')
elif WEBSITE_URL[-1]=='/':
    WEBSITE_URL = WEBSITE_URL[:-1]

WEBSITE_TEMP_DIR = os.environ.get('WEBSITE_TEMP', None)
if WEBSITE_TEMP_DIR==None:
    print('WEBSITE_TEMP not defined (e.g. /tmp/marking)')
    sys.exit(1)

# Exception logging to file
DEBUG_LOGFILE = os.environ.get('WEBSITE_DEBUG_LOG',None)
if DEBUG_LOGFILE != None:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "with_tb": {
                "format": "[{asctime}] [{module}] > {message} >> {exc_info}",
                "style": "{",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "level": "INFO",
            },
            "file_debug": {
                "level": "DEBUG",
                "class": "logging.FileHandler",
                "filename": DEBUG_LOGFILE,
                "formatter": "with_tb",
            },
        },
        "loggers": {
            "django": {
                "handlers": ["console","file_debug"],
                "level": "DEBUG",
            }
        },
    }