# Generated by Django 4.2.14 on 2024-08-20 14:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('short_title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MarkingCombinedGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1024)),
                ('pdf_header_1', models.CharField(max_length=256)),
                ('pdf_header_2', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MarkingRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='web.markingassignment')),
            ],
        ),
        migrations.CreateModel(
            name='MarkingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
                ('ordering', models.IntegerField()),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='web.markingrubric')),
            ],
            options={
                'ordering': ['ordering'],
                'index_together': {('rubric', 'ordering')},
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('value', models.CharField(max_length=256)),
                ('value_type', models.IntegerField(default=0)),
                ('changed', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('dn', models.CharField(max_length=128)),
                ('bio', models.TextField(blank=True, max_length=4096, null=True)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MarkingStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('gn', models.CharField(max_length=32)),
                ('fn', models.CharField(max_length=32)),
                ('stu_num', models.CharField(max_length=32)),
                ('supervisor', models.CharField(default='', max_length=128)),
            ],
            options={
                'index_together': {('fn', 'gn')},
            },
        ),
        migrations.CreateModel(
            name='MarkingSectionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='web.markingsection')),
            ],
            options={
                'ordering': ['score'],
                'index_together': {('section', 'score')},
            },
        ),
        migrations.CreateModel(
            name='MarkingGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('comments', models.CharField(blank=True, max_length=2048)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.markingassignment')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.supervisor')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.markingrubric')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.markingstudent')),
            ],
            options={
                'index_together': {('rubric', 'marker', 'student'), ('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='MarkingCombinedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.JSONField(blank=True, null=True)),
                ('comments', models.TextField(max_length=8192)),
                ('combined', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.markingcombinedgrading')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.markingstudent')),
            ],
        ),
        migrations.CreateModel(
            name='MarkingGradingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('comment', models.TextField(blank=True, max_length=2048)),
                ('grading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='web.markinggrading')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.markingsectionresponse')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.markingsection')),
            ],
            options={
                'unique_together': {('grading', 'section')},
                'index_together': {('grading', 'section', 'response'), ('grading', 'section')},
            },
        ),
        migrations.CreateModel(
            name='MarkingCombinedComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined', to='web.markingassignment')),
                ('combined', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='web.markingcombinedgrading')),
            ],
            options={
                'index_together': {('combined', 'order')},
            },
        ),
    ]
