# Generated by Django 5.1.7 on 2025-03-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_markingstudent_username'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='markingcombinedcomponent',
            new_name='web_marking_combine_8369ac_idx',
            old_fields=('combined', 'order'),
        ),
        migrations.RenameIndex(
            model_name='markinggrading',
            new_name='web_marking_assignm_c35321_idx',
            old_fields=('assignment', 'student'),
        ),
        migrations.RenameIndex(
            model_name='markinggrading',
            new_name='web_marking_rubric__076ca0_idx',
            old_fields=('rubric', 'marker', 'student'),
        ),
        migrations.RenameIndex(
            model_name='markinggradingentry',
            new_name='web_marking_grading_922e50_idx',
            old_fields=('grading', 'section', 'response'),
        ),
        migrations.RenameIndex(
            model_name='markinggradingentry',
            new_name='web_marking_grading_fb0c85_idx',
            old_fields=('grading', 'section'),
        ),
        migrations.RenameIndex(
            model_name='markingsection',
            new_name='web_marking_rubric__43b58b_idx',
            old_fields=('rubric', 'ordering'),
        ),
        migrations.RenameIndex(
            model_name='markingsectionresponse',
            new_name='web_marking_section_aaaa9c_idx',
            old_fields=('section', 'score'),
        ),
        migrations.RenameIndex(
            model_name='markingstudent',
            new_name='web_marking_fn_be200b_idx',
            old_fields=('fn', 'gn'),
        ),
    ]
