# Generated by Django 5.1.7 on 2025-04-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_markingcombinedcomponent_combined_order_web_marking_combine_8369ac_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='markingcombinedgrading',
            name='verify_question',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
