# Generated by Django 5.1.7 on 2025-04-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_markingcombinedgrading_verify_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markingstudent',
            name='supervisor',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
