# Generated by Django 5.2.7 on 2025-11-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_alter_markingstudent_supervisor"),
    ]

    operations = [
        migrations.AddField(
            model_name="markingcombinedgrading",
            name="detailed_inc_desc",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="markingcombinedgrading",
            name="detailed_inc_marks",
            field=models.BooleanField(default=False),
        ),
    ]
