# Generated by Django 5.2.1 on 2025-12-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_markingcombinedgrading_detailed_inc_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markingcombinedgrading',
            name='detailed_inc_desc',
            field=models.BooleanField(default=False, help_text='Include description of response in report PDF'),
        ),
        migrations.AlterField(
            model_name='markingcombinedgrading',
            name='detailed_inc_marks',
            field=models.BooleanField(default=False, help_text='Include detailed marks in report PDF'),
        ),
        migrations.AlterField(
            model_name='markingstudent',
            name='fn',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='markingstudent',
            name='gn',
            field=models.CharField(max_length=64),
        ),
    ]
