# Generated by Django 5.2.8 on 2025-12-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_markingcombinedgrading_detailed_inc_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
