# Generated by Django 5.2.17 on 2026-09-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_alter_supervisor_password"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="supervisor",
            constraint=models.UniqueConstraint(
                fields=("username",), name="supervisor_username_unique"
            ),
        ),
    ]
