-- =============================================================================
-- UEA Brief Generator v1.0 schema
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Core tables
-- -----------------------------------------------------------------------------

create table public.assessments (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users (id) on delete cascade,
  title text not null,
  module_code text not null,
  academic_year text not null,
  assessment_type text not null,
  ai_policy text not null,
  group_work_permitted boolean not null default false,
  status text not null default 'draft' check (
    status in ('draft', 'in_review', 'changes_requested', 'approved')
  ),
  content jsonb not null default '{}'::jsonb,
  programme text,
  module_level integer,
  version integer not null default 1 check (version >= 1),
  submitted_at timestamptz,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null check (char_length(trim(display_name)) between 2 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.admin_users (
  user_id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create table public.reviewer_roles (
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null check (
    role in (
      'cluster_lead',
      'ai_reviewer',
      'employability_reviewer',
      'teaching_director'
    )
  ),
  assigned_by uuid not null references auth.users (id),
  created_at timestamptz not null default now(),
  primary key (user_id, role)
);

create table public.cluster_lead_scopes (
  user_id uuid not null references auth.users (id) on delete cascade,
  programme text not null check (char_length(trim(programme)) > 0),
  module_level integer not null,
  assigned_by uuid not null references auth.users (id),
  created_at timestamptz not null default now(),
  primary key (user_id, programme, module_level)
);

create table public.assessment_review_assignments (
  assessment_id uuid not null references public.assessments (id) on delete cascade,
  category text not null check (category in ('academic', 'ai', 'employability')),
  reviewer_id uuid references auth.users (id),
  assigned_by uuid references auth.users (id),
  state text not null default 'pending' check (
    state in ('pending', 'approved', 'changes_requested')
  ),
  reviewed_version integer check (reviewed_version is null or reviewed_version >= 1),
  comment text,
  reviewed_at timestamptz,
  assigned_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (assessment_id, category)
);

create table public.assessment_review_events (
  id bigint generated by default as identity primary key,
  assessment_id uuid not null,
  assessment_version integer not null check (assessment_version >= 1),
  category text check (category is null or category in ('academic', 'ai', 'employability')),
  reviewer_id uuid,
  actor_id uuid,
  action text not null check (
    action in ('assigned', 'submitted', 'approved', 'withdrawn', 'invalidated')
  ),
  comment text,
  created_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------

create index assessments_owner_id_idx on public.assessments (owner_id);
create index assessments_status_idx on public.assessments (status);
create index assessments_academic_year_idx on public.assessments (academic_year);
create index assessments_assessment_type_idx on public.assessments (assessment_type);
create index assessments_updated_at_idx on public.assessments (updated_at desc);
create index reviewer_roles_role_user_id_idx on public.reviewer_roles (role, user_id);
create index cluster_lead_scopes_programme_level_user_idx
  on public.cluster_lead_scopes (programme, module_level, user_id);
create index assessment_review_assignments_reviewer_id_idx
  on public.assessment_review_assignments (reviewer_id);
create index assessment_review_assignments_state_idx
  on public.assessment_review_assignments (state);
create index assessment_review_events_assessment_id_created_at_idx
  on public.assessment_review_events (assessment_id, created_at desc);
create index assessment_review_events_reviewer_id_idx
  on public.assessment_review_events (reviewer_id) where reviewer_id is not null;
create index assessment_review_events_actor_id_idx
  on public.assessment_review_events (actor_id) where actor_id is not null;

-- -----------------------------------------------------------------------------
-- Private authorization and trigger helpers
-- -----------------------------------------------------------------------------

create schema private;
revoke all on schema private from public;
revoke all on schema private from anon;
grant usage on schema private to authenticated;

create function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  new.updated_at := now();
  return new;
end;
$function$;

create function private.workflow_has_oversight_access()
returns boolean
language sql
stable
security definer
set search_path = ''
as $function$
  select auth.uid() is not null
    and (
      exists (
        select 1
        from public.admin_users as au
        where au.user_id = auth.uid()
      )
      or exists (
        select 1
        from public.reviewer_roles as rr
        where rr.user_id = auth.uid()
          and rr.role = 'teaching_director'
      )
    );
$function$;

create function private.workflow_user_can_review_assessment(
  candidate_user_id uuid,
  target_assessment_id uuid,
  target_category text
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $function$
  select candidate_user_id is not null
    and target_category in ('academic', 'ai', 'employability')
    and exists (
      select 1
      from public.assessments as a
      where a.id = target_assessment_id
        and a.owner_id <> candidate_user_id
        and (
          (
            target_category = 'academic'
            and exists (
              select 1
              from public.reviewer_roles as rr
              join public.cluster_lead_scopes as cls
                on cls.user_id = rr.user_id
               and lower(trim(cls.programme)) = lower(trim(a.programme))
               and cls.module_level = a.module_level
              where rr.user_id = candidate_user_id
                and rr.role = 'cluster_lead'
            )
          )
          or (
            target_category = 'ai'
            and exists (
              select 1
              from public.reviewer_roles as rr
              where rr.user_id = candidate_user_id
                and rr.role = 'ai_reviewer'
            )
          )
          or (
            target_category = 'employability'
            and exists (
              select 1
              from public.reviewer_roles as rr
              where rr.user_id = candidate_user_id
                and rr.role = 'employability_reviewer'
            )
          )
        )
    );
$function$;

create function private.workflow_can_review_assessment(
  target_assessment_id uuid,
  target_category text
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $function$
  select private.workflow_user_can_review_assessment(
    auth.uid(), target_assessment_id, target_category
  );
$function$;

create function private.workflow_can_access_assessment(
  target_assessment_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $function$
  select auth.uid() is not null
    and exists (
      select 1
      from public.assessments as a
      where a.id = target_assessment_id
        and (
          a.owner_id = auth.uid()
          or private.workflow_has_oversight_access()
          or (
            a.status <> 'draft'
            and (
              private.workflow_user_can_review_assessment(
                auth.uid(), a.id, 'academic'
              )
              or private.workflow_user_can_review_assessment(
                auth.uid(), a.id, 'ai'
              )
              or private.workflow_user_can_review_assessment(
                auth.uid(), a.id, 'employability'
              )
            )
          )
        )
    );
$function$;
create function private.prepare_assessment_version_update()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
declare
  brief_changed boolean;
  workflow_transition_allowed boolean;
begin
  new.programme := nullif(trim(new.programme), '');

  if tg_op = 'INSERT' then
    new.version := 1;
    new.status := 'draft';
    new.submitted_at := null;
    new.approved_at := null;
    return new;
  end if;

  brief_changed :=
    new.title is distinct from old.title
    or new.module_code is distinct from old.module_code
    or new.academic_year is distinct from old.academic_year
    or new.assessment_type is distinct from old.assessment_type
    or new.ai_policy is distinct from old.ai_policy
    or new.group_work_permitted is distinct from old.group_work_permitted
    or new.content is distinct from old.content
    or new.programme is distinct from old.programme
    or new.module_level is distinct from old.module_level;
  workflow_transition_allowed :=
    coalesce(pg_catalog.current_setting('app.workflow_transition', true), '') = 'allowed';

  if brief_changed then
    if old.status <> 'draft' then
      new.version := old.version + 1;
      new.status := 'draft';
      new.submitted_at := null;
      new.approved_at := null;
    else
      new.version := old.version;
      new.status := old.status;
      new.submitted_at := old.submitted_at;
      new.approved_at := old.approved_at;
    end if;
  elsif (
    new.version is distinct from old.version
    or new.status is distinct from old.status
    or new.submitted_at is distinct from old.submitted_at
    or new.approved_at is distinct from old.approved_at
  ) and not workflow_transition_allowed then
    raise exception 'Assessment workflow fields can only be changed through workflow actions'
      using errcode = '42501';
  end if;

  return new;
end;
$function$;

create function private.invalidate_assessment_reviews()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  update public.assessment_review_assignments as ara
  set reviewer_id = null,
      assigned_by = null,
      state = 'pending',
      reviewed_version = null,
      comment = null,
      reviewed_at = null
  where ara.assessment_id = new.id;

  insert into public.assessment_review_events (
    assessment_id,
    assessment_version,
    actor_id,
    action,
    comment
  ) values (
    new.id,
    new.version,
    auth.uid(),
    'invalidated',
    'Assessment brief changed; version ' || old.version::text
      || ' reviews were invalidated by version ' || new.version::text
  );

  return new;
end;
$function$;

-- -----------------------------------------------------------------------------
-- Timestamp and workflow triggers
-- -----------------------------------------------------------------------------

create trigger assessments_set_updated_at
before update on public.assessments
for each row execute function private.set_updated_at();

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function private.set_updated_at();

create trigger assessment_review_assignments_set_updated_at
before update on public.assessment_review_assignments
for each row execute function private.set_updated_at();

create trigger assessments_prepare_version_update
before insert or update on public.assessments
for each row execute function private.prepare_assessment_version_update();

create trigger assessments_invalidate_reviews
after update of version on public.assessments
for each row
when (old.version is distinct from new.version)
execute function private.invalidate_assessment_reviews();

revoke all on function private.set_updated_at() from public, anon, authenticated;
revoke all on function private.prepare_assessment_version_update() from public, anon, authenticated;
revoke all on function private.invalidate_assessment_reviews() from public, anon, authenticated;
revoke all on function private.workflow_has_oversight_access() from public, anon;
grant execute on function private.workflow_has_oversight_access() to authenticated;
revoke all on function private.workflow_user_can_review_assessment(uuid, uuid, text)
  from public, anon, authenticated;
revoke all on function private.workflow_can_review_assessment(uuid, text) from public, anon;
grant execute on function private.workflow_can_review_assessment(uuid, text) to authenticated;
revoke all on function private.workflow_can_access_assessment(uuid) from public, anon;
grant execute on function private.workflow_can_access_assessment(uuid) to authenticated;

-- -----------------------------------------------------------------------------
-- Row-level security, table grants, and owner access
-- -----------------------------------------------------------------------------

-- PostgREST roles need schema usage before table grants and RLS can apply.
grant usage on schema public to anon, authenticated;

alter table public.assessments enable row level security;
alter table public.profiles enable row level security;
alter table public.admin_users enable row level security;
alter table public.reviewer_roles enable row level security;
alter table public.cluster_lead_scopes enable row level security;
alter table public.assessment_review_assignments enable row level security;
alter table public.assessment_review_events enable row level security;

revoke all on table public.assessments from public, anon, authenticated;
grant select, insert, delete on table public.assessments to authenticated;
grant update (
  title,
  module_code,
  academic_year,
  assessment_type,
  ai_policy,
  group_work_permitted,
  content,
  programme,
  module_level
) on table public.assessments to authenticated;

revoke all on table public.profiles from public, anon, authenticated;
grant select, insert, update (user_id, display_name) on table public.profiles to authenticated;

revoke all on table public.admin_users from public, anon, authenticated;
grant select on table public.admin_users to authenticated;

revoke all on table public.reviewer_roles from public, anon, authenticated;
grant select on table public.reviewer_roles to authenticated;

revoke all on table public.cluster_lead_scopes from public, anon, authenticated;
grant select on table public.cluster_lead_scopes to authenticated;

revoke all on table public.assessment_review_assignments from public, anon, authenticated;
grant select on table public.assessment_review_assignments to authenticated;

revoke all on table public.assessment_review_events from public, anon, authenticated;
grant select on table public.assessment_review_events to authenticated;
revoke all on sequence public.assessment_review_events_id_seq from public, anon, authenticated;

create policy "Users can read own assessments"
on public.assessments for select to authenticated
using ((select auth.uid()) = owner_id);

create policy "Users can create own assessments"
on public.assessments for insert to authenticated
with check ((select auth.uid()) = owner_id);

create policy "Users can update own assessments"
on public.assessments for update to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

create policy "Users can delete own assessments"
on public.assessments for delete to authenticated
using ((select auth.uid()) = owner_id);

create policy "Oversight users can read all assessments"
on public.assessments for select to authenticated
using ((select private.workflow_has_oversight_access()));

create policy "Eligible reviewers can read submitted assessments"
on public.assessments for select to authenticated
using (
  status <> 'draft'
  and (
    (select private.workflow_can_review_assessment(id, 'academic'))
    or (select private.workflow_can_review_assessment(id, 'ai'))
    or (select private.workflow_can_review_assessment(id, 'employability'))
  )
);

create policy "Authenticated users can read profiles"
on public.profiles for select to authenticated using (true);

create policy "Users can create own profile"
on public.profiles for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update own profile"
on public.profiles for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can read own admin membership"
on public.admin_users for select to authenticated
using (
  user_id = (select auth.uid())
  or (select private.workflow_has_oversight_access())
);

create policy "Users can read own workflow roles and admins can read all"
on public.reviewer_roles for select to authenticated
using (
  user_id = (select auth.uid())
  or (select private.workflow_has_oversight_access())
);

create policy "Users can read own cluster scopes and admins can read all"
on public.cluster_lead_scopes for select to authenticated
using (
  user_id = (select auth.uid())
  or (select private.workflow_has_oversight_access())
);

create policy "Assessment participants can read review assignments"
on public.assessment_review_assignments for select to authenticated
using ((select private.workflow_can_access_assessment(assessment_id)));

create policy "Assessment participants can read review events"
on public.assessment_review_events for select to authenticated
using (
  (select private.workflow_can_access_assessment(assessment_id))
  or reviewer_id = (select auth.uid())
  or actor_id = (select auth.uid())
);

-- -----------------------------------------------------------------------------
-- Public workflow and administration RPCs
-- -----------------------------------------------------------------------------

create function public.admin_cluster_lead_scopes()
returns table (
  user_id uuid,
  programme text,
  module_level integer,
  assigned_by uuid,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if not private.workflow_has_oversight_access() then
    raise exception 'Administrator or Teaching Director access required'
      using errcode = '42501';
  end if;

  return query
  select
    cls.user_id,
    cls.programme,
    cls.module_level,
    cls.assigned_by,
    cls.created_at
  from public.cluster_lead_scopes as cls
  order by lower(cls.programme), cls.module_level, cls.user_id;
end;
$function$;

create function public.admin_set_cluster_lead_scope(
  target_user_id uuid,
  target_programme text,
  target_module_level integer,
  enabled boolean
)
returns void
language plpgsql
security definer
set search_path = ''
as $function$
declare
  normalized_programme text;
begin
  if not private.workflow_has_oversight_access() then
    raise exception 'Administrator or Teaching Director access required'
      using errcode = '42501';
  end if;

  normalized_programme := nullif(trim(target_programme), '');
  if target_user_id is null
    or normalized_programme is null
    or target_module_level is null then
    raise exception 'User, programme, and module level are required'
      using errcode = '22023';
  end if;

  if enabled is null then
    raise exception 'enabled must be true or false' using errcode = '22023';
  end if;

  if enabled and not exists (
    select 1
    from public.reviewer_roles as rr
    where rr.user_id = target_user_id
      and rr.role = 'cluster_lead'
  ) then
    raise exception 'User must hold the cluster_lead role'
      using errcode = '22023';
  end if;

  if enabled then
    insert into public.cluster_lead_scopes (
      user_id,
      programme,
      module_level,
      assigned_by
    ) values (
      target_user_id,
      normalized_programme,
      target_module_level,
      auth.uid()
    )
    on conflict (user_id, programme, module_level) do update
      set assigned_by = excluded.assigned_by,
          created_at = now();
  else
    delete from public.cluster_lead_scopes as cls
    where cls.user_id = target_user_id
      and cls.programme = normalized_programme
      and cls.module_level = target_module_level;
  end if;
end;
$function$;
create function public.admin_review_workflow_users()
returns table (
  user_id uuid,
  display_name text,
  cluster_lead boolean,
  ai_reviewer boolean,
  employability_reviewer boolean,
  teaching_director boolean
)
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if not private.workflow_has_oversight_access() then
    raise exception 'Administrator or Teaching Director access required'
      using errcode = '42501';
  end if;

  return query
  select
    p.user_id,
    p.display_name,
    exists (
      select 1 from public.reviewer_roles as rr
      where rr.user_id = p.user_id and rr.role = 'cluster_lead'
    ) as cluster_lead,
    exists (
      select 1 from public.reviewer_roles as rr
      where rr.user_id = p.user_id and rr.role = 'ai_reviewer'
    ) as ai_reviewer,
    exists (
      select 1 from public.reviewer_roles as rr
      where rr.user_id = p.user_id and rr.role = 'employability_reviewer'
    ) as employability_reviewer,
    exists (
      select 1 from public.reviewer_roles as rr
      where rr.user_id = p.user_id and rr.role = 'teaching_director'
    ) as teaching_director
  from public.profiles as p
  order by lower(p.display_name), p.user_id;
end;
$function$;

create function public.admin_set_workflow_role(
  target_user_id uuid,
  target_role text,
  enabled boolean
)
returns void
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if not private.workflow_has_oversight_access() then
    raise exception 'Administrator or Teaching Director access required'
      using errcode = '42501';
  end if;

  if target_role is null or target_role not in (
    'cluster_lead',
    'ai_reviewer',
    'employability_reviewer',
    'teaching_director'
  ) then
    raise exception 'Invalid workflow role: %', target_role using errcode = '22023';
  end if;

  if enabled is null then
    raise exception 'enabled must be true or false' using errcode = '22023';
  end if;

  if target_user_id is null or not exists (
    select 1
    from public.profiles as p
    where p.user_id = target_user_id
  ) then
    raise exception 'Cannot set workflow role without an existing profile: %', target_user_id
      using errcode = '22023';
  end if;

  if enabled then
    insert into public.reviewer_roles (user_id, role, assigned_by)
    values (target_user_id, target_role, auth.uid())
    on conflict (user_id, role) do update
      set assigned_by = excluded.assigned_by;
  else
    if target_role = 'cluster_lead' then
      delete from public.cluster_lead_scopes as cls
      where cls.user_id = target_user_id;
    end if;

    delete from public.reviewer_roles as rr
    where rr.user_id = target_user_id
      and rr.role = target_role;
  end if;
end;
$function$;

create function public.admin_review_assignments()
returns table (
  assessment_id uuid,
  category text,
  reviewer_id uuid,
  reviewer_name text,
  state text,
  reviewed_version integer,
  comment text,
  reviewed_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if not private.workflow_has_oversight_access() then
    raise exception 'Administrator or Teaching Director access required'
      using errcode = '42501';
  end if;

  return query
  select
    ara.assessment_id,
    ara.category,
    ara.reviewer_id,
    p.display_name as reviewer_name,
    ara.state,
    ara.reviewed_version,
    ara.comment,
    ara.reviewed_at
  from public.assessment_review_assignments as ara
  left join public.profiles as p on p.user_id = ara.reviewer_id
  order by ara.assessment_id,
    case ara.category
      when 'academic' then 1
      when 'ai' then 2
      when 'employability' then 3
    end;
end;
$function$;

create function public.submit_assessment_for_review(
  target_assessment_id uuid
)
returns void
language plpgsql
security definer
set search_path = ''
as $function$
declare
  assessment_current_version integer;
  assessment_current_status text;
  assessment_owner_id uuid;
  assessment_programme text;
  assessment_module_level integer;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  select a.version, a.status, a.owner_id, a.programme, a.module_level
  into assessment_current_version, assessment_current_status,
    assessment_owner_id, assessment_programme, assessment_module_level
  from public.assessments as a
  where a.id = target_assessment_id
    and a.owner_id = auth.uid()
  for update;

  if not found then
    raise exception 'Assessment owner access required' using errcode = '42501';
  end if;

  if assessment_current_status <> 'draft' then
    raise exception 'Only draft assessments can be submitted for review'
      using errcode = '22023';
  end if;

  if assessment_programme is null or assessment_module_level is null then
    raise exception 'Programme and module level are required before submission'
      using errcode = '22023';
  end if;

  if not exists (
    select 1
    from public.reviewer_roles as rr
    join public.cluster_lead_scopes as cls
      on cls.user_id = rr.user_id
     and lower(trim(cls.programme)) = lower(trim(assessment_programme))
     and cls.module_level = assessment_module_level
    where rr.role = 'cluster_lead'
      and rr.user_id <> assessment_owner_id
  ) then
    raise exception 'An eligible non-owner cluster lead is required for this programme and level'
      using errcode = '22023';
  end if;

  if not exists (
    select 1
    from public.reviewer_roles as rr
    where rr.role = 'ai_reviewer'
      and rr.user_id <> assessment_owner_id
  ) then
    raise exception 'An eligible non-owner AI reviewer is required'
      using errcode = '22023';
  end if;

  if not exists (
    select 1
    from public.reviewer_roles as rr
    where rr.role = 'employability_reviewer'
      and rr.user_id <> assessment_owner_id
  ) then
    raise exception 'An eligible non-owner employability reviewer is required'
      using errcode = '22023';
  end if;

  insert into public.assessment_review_assignments (
    assessment_id,
    category,
    reviewer_id,
    assigned_by,
    state,
    reviewed_version,
    comment,
    reviewed_at,
    assigned_at
  )
  select
    target_assessment_id,
    required_categories.category,
    null,
    null,
    'pending',
    null,
    null,
    null,
    now()
  from (
    values ('academic'::text), ('ai'::text), ('employability'::text)
  ) as required_categories(category)
  on conflict (assessment_id, category) do update
    set reviewer_id = null,
        assigned_by = null,
        state = 'pending',
        reviewed_version = null,
        comment = null,
        reviewed_at = null,
        assigned_at = excluded.assigned_at;

  perform pg_catalog.set_config('app.workflow_transition', 'allowed', true);

  update public.assessments as a
  set status = 'in_review',
      submitted_at = now(),
      approved_at = null
  where a.id = target_assessment_id;

  insert into public.assessment_review_events (
    assessment_id,
    assessment_version,
    actor_id,
    action
  ) values (
    target_assessment_id,
    assessment_current_version,
    auth.uid(),
    'submitted'
  );
end;
$function$;
create function public.assessment_review_status(
  target_assessment_id uuid
)
returns table (
  category text,
  reviewer_id uuid,
  reviewer_name text,
  state text,
  reviewed_version integer,
  comment text,
  reviewed_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if auth.uid() is null
    or not private.workflow_can_access_assessment(target_assessment_id) then
    raise exception 'Assessment review access required' using errcode = '42501';
  end if;

  return query
  select
    ara.category,
    ara.reviewer_id,
    p.display_name as reviewer_name,
    ara.state,
    ara.reviewed_version,
    ara.comment,
    ara.reviewed_at
  from public.assessment_review_assignments as ara
  left join public.profiles as p on p.user_id = ara.reviewer_id
  where ara.assessment_id = target_assessment_id
  order by case ara.category
    when 'academic' then 1
    when 'ai' then 2
    when 'employability' then 3
  end;
end;
$function$;

create function public.assessment_can_export_final(
  target_assessment_id uuid
)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $function$
declare
  assessment_current_version integer;
  assessment_current_status text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  select a.version, a.status
  into assessment_current_version, assessment_current_status
  from public.assessments as a
  where a.id = target_assessment_id
    and a.owner_id = auth.uid();

  if not found then
    raise exception 'Only the assessment owner can export the final brief'
      using errcode = '42501';
  end if;

  return assessment_current_status = 'approved'
    and (
      select count(*) = 3
        and count(distinct ara.category) = 3
      from public.assessment_review_assignments as ara
      where ara.assessment_id = target_assessment_id
        and ara.category in ('academic', 'ai', 'employability')
        and ara.state = 'approved'
        and ara.reviewer_id is not null
        and ara.reviewed_version = assessment_current_version
    );
end;
$function$;
create function public.review_queue()
returns table (
  assessment_id uuid,
  title text,
  module_code text,
  owner_id uuid,
  owner_name text,
  category text,
  reviewer_id uuid,
  state text,
  assessment_version integer,
  reviewed_version integer,
  comment text,
  submitted_at timestamptz,
  status text,
  content jsonb,
  updated_at timestamptz,
  can_review boolean
)
language plpgsql
security definer
set search_path = ''
as $function$
declare
  caller_has_oversight boolean;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  caller_has_oversight := private.workflow_has_oversight_access();

  return query
  select
    a.id as assessment_id,
    a.title,
    a.module_code,
    a.owner_id,
    owner_profile.display_name as owner_name,
    required_categories.category,
    ara.reviewer_id,
    coalesce(ara.state, 'pending') as state,
    a.version as assessment_version,
    ara.reviewed_version,
    ara.comment,
    a.submitted_at,
    a.status,
    a.content,
    a.updated_at,
    (
      a.status in ('in_review', 'approved')
      and private.workflow_user_can_review_assessment(
        auth.uid(), a.id, required_categories.category
      )
    ) as can_review
  from public.assessments as a
  cross join (
    values ('academic'::text), ('ai'::text), ('employability'::text)
  ) as required_categories(category)
  left join public.assessment_review_assignments as ara
    on ara.assessment_id = a.id
   and ara.category = required_categories.category
  left join public.profiles as owner_profile on owner_profile.user_id = a.owner_id
  where caller_has_oversight
    or (
      a.status <> 'draft'
      and private.workflow_user_can_review_assessment(
        auth.uid(), a.id, required_categories.category
      )
    )
  order by a.submitted_at desc nulls last,
    a.updated_at desc,
    case required_categories.category
      when 'academic' then 1
      when 'ai' then 2
      when 'employability' then 3
    end;
end;
$function$;

create function public.admin_list_users()
returns table (
  user_id uuid,
  display_name text,
  is_admin boolean
)
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if not private.workflow_has_oversight_access() then
    raise exception 'Administrator or Teaching Director access required'
      using errcode = '42501';
  end if;

  return query
  select
    p.user_id,
    p.display_name,
    au.user_id is not null as is_admin
  from public.profiles as p
  left join public.admin_users as au on au.user_id = p.user_id
  order by lower(p.display_name), p.user_id;
end;
$function$;

create function public.admin_promote_user(target_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if not private.workflow_has_oversight_access() then
    raise exception 'Administrator or Teaching Director access required'
      using errcode = '42501';
  end if;

  if target_user_id is null or not exists (
    select 1
    from public.profiles as p
    where p.user_id = target_user_id
  ) then
    raise exception 'Cannot promote user without an existing profile: %', target_user_id
      using errcode = '22023';
  end if;

  insert into public.admin_users (user_id)
  values (target_user_id)
  on conflict (user_id) do nothing;
end;
$function$;

create function public.admin_demote_user(target_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if not private.workflow_has_oversight_access() then
    raise exception 'Administrator or Teaching Director access required'
      using errcode = '42501';
  end if;

  if target_user_id is null then
    raise exception 'Administrator user is required' using errcode = '22023';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext('public.admin_users_role_management')
  );

  if not exists (
    select 1
    from public.admin_users as au
    where au.user_id = target_user_id
  ) then
    return;
  end if;

  if target_user_id = auth.uid() then
    raise exception 'You cannot demote your own administrator account'
      using errcode = '22023';
  end if;

  if (select count(*) from public.admin_users) <= 1 then
    raise exception 'The final administrator cannot be demoted'
      using errcode = '22023';
  end if;

  delete from public.admin_users as au
  where au.user_id = target_user_id;
end;
$function$;

create function public.admin_assessment_statistics()
returns table (
  total_assessments bigint,
  unique_owners bigint,
  group_work_assessments bigint,
  assessments_by_status jsonb,
  assessments_by_type jsonb,
  assessments_by_academic_year jsonb
)
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if not private.workflow_has_oversight_access() then
    raise exception 'Administrator or Teaching Director access required'
      using errcode = '42501';
  end if;

  return query
  select
    count(*)::bigint,
    count(distinct assessments.owner_id)::bigint,
    count(*) filter (where assessments.group_work_permitted)::bigint,
    coalesce(
      (
        select jsonb_object_agg(status_counts.status, status_counts.assessment_count)
        from (
          select a.status, count(*)::bigint as assessment_count
          from public.assessments as a
          group by a.status
        ) as status_counts
      ),
      '{}'::jsonb
    ),
    coalesce(
      (
        select jsonb_object_agg(type_counts.assessment_type, type_counts.assessment_count)
        from (
          select a.assessment_type, count(*)::bigint as assessment_count
          from public.assessments as a
          group by a.assessment_type
        ) as type_counts
      ),
      '{}'::jsonb
    ),
    coalesce(
      (
        select jsonb_object_agg(year_counts.academic_year, year_counts.assessment_count)
        from (
          select a.academic_year, count(*)::bigint as assessment_count
          from public.assessments as a
          group by a.academic_year
        ) as year_counts
      ),
      '{}'::jsonb
    )
  from public.assessments as assessments;
end;
$function$;
create function public.record_assessment_review(
  target_assessment_id uuid,
  target_category text,
  decision text,
  review_comment text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $function$
declare
  assessment_current_version integer;
  assessment_current_status text;
  assessment_owner_id uuid;
  category_current_state text;
  category_reviewed_version integer;
  normalized_decision text;
  normalized_comment text;
  all_categories_approved boolean;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if target_category is null
    or target_category not in ('academic', 'ai', 'employability') then
    raise exception 'Invalid review category: %', target_category
      using errcode = '22023';
  end if;

  normalized_decision := lower(trim(decision));
  if normalized_decision is null
    or normalized_decision not in ('approve', 'withdraw') then
    raise exception 'Decision must be approve or withdraw'
      using errcode = '22023';
  end if;

  normalized_comment := nullif(trim(review_comment), '');
  if normalized_decision = 'withdraw'
    and (normalized_comment is null or char_length(normalized_comment) < 2) then
    raise exception 'A withdrawal comment of at least 2 characters is required'
      using errcode = '22023';
  end if;

  select a.version, a.status, a.owner_id
  into assessment_current_version, assessment_current_status, assessment_owner_id
  from public.assessments as a
  where a.id = target_assessment_id
  for update;

  if not found then
    raise exception 'Assessment not found: %', target_assessment_id
      using errcode = '22023';
  end if;

  if assessment_current_status not in ('in_review', 'approved') then
    raise exception 'Assessment is not available for review'
      using errcode = '22023';
  end if;

  if auth.uid() = assessment_owner_id then
    raise exception 'Assessment owners cannot review their own assessment'
      using errcode = '42501';
  end if;

  if not private.workflow_user_can_review_assessment(
    auth.uid(), target_assessment_id, target_category
  ) then
    raise exception 'Reviewer role and scope eligibility required'
      using errcode = '42501';
  end if;

  select ara.state, ara.reviewed_version
  into category_current_state, category_reviewed_version
  from public.assessment_review_assignments as ara
  where ara.assessment_id = target_assessment_id
    and ara.category = target_category
  for update;

  if not found then
    raise exception 'Assessment category is not pending review'
      using errcode = '22023';
  end if;

  if normalized_decision = 'approve'
    and category_current_state = 'approved'
    and category_reviewed_version = assessment_current_version then
    raise exception 'This category is already approved for the current version'
      using errcode = '22023';
  end if;

  perform pg_catalog.set_config('app.workflow_transition', 'allowed', true);

  if normalized_decision = 'withdraw' then
    update public.assessment_review_assignments as ara
    set reviewer_id = auth.uid(),
        assigned_by = null,
        state = 'changes_requested',
        reviewed_version = assessment_current_version,
        comment = normalized_comment,
        reviewed_at = now()
    where ara.assessment_id = target_assessment_id
      and ara.category = target_category;

    update public.assessments as a
    set status = 'changes_requested',
        approved_at = null
    where a.id = target_assessment_id;

    insert into public.assessment_review_events (
      assessment_id,
      assessment_version,
      category,
      reviewer_id,
      actor_id,
      action,
      comment
    ) values (
      target_assessment_id,
      assessment_current_version,
      target_category,
      auth.uid(),
      auth.uid(),
      'withdrawn',
      normalized_comment
    );
  else
    update public.assessment_review_assignments as ara
    set reviewer_id = auth.uid(),
        assigned_by = null,
        state = 'approved',
        reviewed_version = assessment_current_version,
        comment = normalized_comment,
        reviewed_at = now()
    where ara.assessment_id = target_assessment_id
      and ara.category = target_category;

    insert into public.assessment_review_events (
      assessment_id,
      assessment_version,
      category,
      reviewer_id,
      actor_id,
      action,
      comment
    ) values (
      target_assessment_id,
      assessment_current_version,
      target_category,
      auth.uid(),
      auth.uid(),
      'approved',
      normalized_comment
    );

    select count(*) = 3
      and count(distinct ara.category) = 3
    into all_categories_approved
    from public.assessment_review_assignments as ara
    where ara.assessment_id = target_assessment_id
      and ara.category in ('academic', 'ai', 'employability')
      and ara.state = 'approved'
      and ara.reviewer_id is not null
      and ara.reviewed_version = assessment_current_version;

    update public.assessments as a
    set status = case
          when all_categories_approved then 'approved'
          else 'in_review'
        end,
        approved_at = case
          when all_categories_approved then now()
          else null
        end
    where a.id = target_assessment_id;
  end if;
end;
$function$;

-- -----------------------------------------------------------------------------
-- RPC execution grants
-- -----------------------------------------------------------------------------

revoke all on function public.admin_assessment_statistics() from public, anon;
revoke all on function public.admin_demote_user(uuid) from public, anon;
revoke all on function public.admin_list_users() from public, anon;
revoke all on function public.admin_promote_user(uuid) from public, anon;
revoke all on function public.admin_cluster_lead_scopes() from public, anon;
revoke all on function public.admin_review_assignments() from public, anon;
revoke all on function public.admin_review_workflow_users() from public, anon;
revoke all on function public.admin_set_cluster_lead_scope(uuid, text, integer, boolean) from public, anon;
revoke all on function public.admin_set_workflow_role(uuid, text, boolean) from public, anon;
revoke all on function public.assessment_can_export_final(uuid) from public, anon;
revoke all on function public.assessment_review_status(uuid) from public, anon;
revoke all on function public.record_assessment_review(uuid, text, text, text) from public, anon;
revoke all on function public.review_queue() from public, anon;
revoke all on function public.submit_assessment_for_review(uuid) from public, anon;

grant execute on function public.admin_assessment_statistics() to authenticated;
grant execute on function public.admin_demote_user(uuid) to authenticated;
grant execute on function public.admin_list_users() to authenticated;
grant execute on function public.admin_promote_user(uuid) to authenticated;
grant execute on function public.admin_cluster_lead_scopes() to authenticated;
grant execute on function public.admin_review_assignments() to authenticated;
grant execute on function public.admin_review_workflow_users() to authenticated;
grant execute on function public.admin_set_cluster_lead_scope(uuid, text, integer, boolean) to authenticated;
grant execute on function public.admin_set_workflow_role(uuid, text, boolean) to authenticated;
grant execute on function public.assessment_can_export_final(uuid) to authenticated;
grant execute on function public.assessment_review_status(uuid) to authenticated;
grant execute on function public.record_assessment_review(uuid, text, text, text) to authenticated;
grant execute on function public.review_queue() to authenticated;
grant execute on function public.submit_assessment_for_review(uuid) to authenticated;
